"""Optical analysis: imaging (spots, PSF, contrast) and aberrations (field
metrics, distortion, wavefront/Zernike, fans, stigmatism).

Everything below is also importable from its actual subpackage
(``raytracer.analysis.imaging`` / ``raytracer.analysis.aberrations``); this
top-level re-export exists so existing call sites don't need to know which
side of that split a given name lives on.
"""

from .aberrations import (
    AxialColor,
    DistortionGrid,
    FanData,
    LateralColor,
    Mode,
    SeidelCoefficients,
    StigmatismReport,
    WavefrontSamples,
    ZernikeExpansion,
    axial_color,
    distortion_grid,
    export_metrics_csv,
    exit_pupil_wavefront,
    field_metrics,
    fit_opd,
    fit_transverse,
    lateral_color,
    point_line_distances,
    ray_fans,
    rays_by_generation,
    seidel_coefficients,
    stigmatism_report,
    zernike,
    zernike_modes,
)
from .imaging import (
    BinaryMask,
    PupilGrid,
    SpotData,
    abbe_image,
    airy_radius_mm,
    coherent_cutoff_half_pitch_nm,
    contrast_curve,
    pupil_function,
    scalar_psf,
    spot_data,
    spot_data_from_points,
)

__all__ = [
    "AxialColor",
    "LateralColor",
    "axial_color",
    "lateral_color",
    "DistortionGrid",
    "distortion_grid",
    "SeidelCoefficients",
    "seidel_coefficients",
    "SpotData",
    "spot_data",
    "spot_data_from_points",
    "StigmatismReport",
    "stigmatism_report",
    "point_line_distances",
    "rays_by_generation",
    "FanData",
    "ray_fans",
    "field_metrics",
    "export_metrics_csv",
    "Mode",
    "zernike",
    "zernike_modes",
    "ZernikeExpansion",
    "fit_transverse",
    "fit_opd",
    "WavefrontSamples",
    "exit_pupil_wavefront",
    "PupilGrid",
    "pupil_function",
    "scalar_psf",
    "airy_radius_mm",
    "BinaryMask",
    "abbe_image",
    "contrast_curve",
    "coherent_cutoff_half_pitch_nm",
]
